# Generated by Django 5.0.6 on 2024-07-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_rename_created_at_mytodo_due_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytodo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
